###
###
###
###   Purpose:   Create skeleton documentation
###   started:   2016/02/16 (pvr)
###
### ############################################################ ###

#' Create a new Rmarkdown (Rmd) document
#'
#' @description
#' \code{create_docu_skeleton} assumes that psPkgPath is a
#' directory that contains an R-package. By default the new
#' document is created in subdirectory "vignettes". If this
#' subdirectory does not exist, it is created. The document
#' is generated by the function \code{rmarkdown::draft} using
#' the template "project_docu".
#'
#' @details
#' The basic functionality follows the function
#' \code{devtools::use_vignette}, except for the possibility
#' of specifying any given template from any package.
#'
#' @param   psDocuName   name of the new document
#' @param   psPath       parent directory of rmd source dir
#' @export create_docu_skeleton
create_docu_skeleton <- function(psDocuName,
                                 psPkgPath     = ".",
                                 psRmdTemplate = "project_docu",
                                 psTemplatePkg = "rqudocuhelper",
                                 psDocuSubdir  = "vignettes",
                                 pbEdit        = FALSE) {
  ### # do the preparation similar to devtools::use_vignette
  pkg <- devtools::as.package(psPkgPath)
  devtools:::check_suggested("rmarkdown")
  devtools:::add_desc_package(pkg, "Suggests", "knitr")
  devtools:::add_desc_package(pkg, "Suggests", "rmarkdown")
  devtools:::add_desc_package(pkg, "VignetteBuilder", "knitr")
  dir.create(file.path(pkg$path, psDocuSubdir), showWarnings = FALSE)
  sDocuPath <- file.path(pkg$path, psDocuSubdir, paste0(psDocuName, ".Rmd"))
  rmarkdown::draft(file = sDocuPath,
                   template = psRmdTemplate,
                   package = psTemplatePkg,
                   create_dir = FALSE,
                   edit = FALSE)
  if (pbEdit) file.edit(sDocuPath)
  message("Draft vignette created in ", sDocuPath)

}

#' Adding a string to .gitignore
add_git_ignore <- function (psPath = ".", psIgnores)
{
  sPath <- file.path(psPath, ".gitignore")
  union_write(sPath, psIgnores)
  invisible(TRUE)
}

#' write a string to an existing file
union_write <- function (path, new_lines)
{
  if (file.exists(path)) {
    lines <- readLines(path, warn = FALSE)
  }
  else {
    lines <- character()
  }
  all <- union(lines, new_lines)
  writeLines(all, path)
}
